Merged revisions 298905 via svnmerge from file:///srv/subversion/repos/asterisk/branches/1.4
........
  r298905 | tilghman | 2010-12-17 15:40:56 -0600 (Fri, 17 Dec 2010) | 6 lines
  
  Let Asterisk find better backtrace information with libbfd.
  
  The menuselect option BETTER_BACKTRACES, if enabled, will use libbfd to search
  for better symbol information within both the Asterisk binary, as well as
  loaded modules, to assist when using inline backtraces to track down problems.
........


git-svn-id: https://origsvn.digium.com/svn/asterisk/team/oej/bp-res_conf_ldap-1.4@298924 65c4cc65-6c06-0410-ace0-fbb531ad65f3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -730,6 +730,10 @@ ALSA_LIB
 ALSA_INCLUDE
 ALSA_DIR
 PBX_ALSA
+BFD_LIB
+BFD_INCLUDE
+BFD_DIR
+PBX_BFD
 CAP_LIB
 CAP_INCLUDE
 CAP_DIR
@@ -923,6 +927,7 @@ GC_LDFLAGS
 AST_DECLARATION_AFTER_STATEMENT
 AST_FORTIFY_SOURCE
 AST_NO_STRICT_OVERFLOW
+PBX_DLADDR
 PBX_DAHDI_TRANSCODE
 GSM_INTERNAL
 KDEINIT
@@ -1548,6 +1553,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-asound=PATH      use Advanced Linux Sound Architecture files in PATH
+  --with-bfd=PATH         use Debug symbol decoding files in PATH
   --with-cap=PATH         use POSIX 1.e capabilities files in PATH
   --with-curses=PATH      use curses files in PATH
   --with-dahdi=PATH       use DAHDI files in PATH
@@ -8080,6 +8086,36 @@ esac
 fi
 
 PBX_ALSA=0
+
+
+
+
+
+
+
+
+BFD_DESCRIP="Debug symbol decoding"
+BFD_OPTION="bfd"
+
+# Check whether --with-bfd was given.
+if test "${with_bfd+set}" = set; then
+  withval=$with_bfd;
+case ${withval} in
+     n|no)
+     USE_BFD=no
+     ;;
+     y|ye|yes)
+     BFD_MANDATORY="yes"
+     ;;
+     *)
+     BFD_DIR="${withval}"
+     BFD_MANDATORY="yes"
+     ;;
+esac
+
+fi
+
+PBX_BFD=0
 
 
 
@@ -19646,6 +19682,68 @@ _ACEOF
 
 fi ; fi ; fi
 
+{ echo "$as_me:$LINENO: checking for dladdr in dlfcn.h" >&5
+echo $ECHO_N "checking for dladdr in dlfcn.h... $ECHO_C" >&6; }
+PBX_DLADDR=0
+old_LIBS=${LIBS}
+LIBS="${LIBS} -ldl"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#define _GNU_SOURCE 1
+#include <dlfcn.h>
+int
+main ()
+{
+dladdr((void *)0, (void *)0)
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	PBX_DLADDR=1
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DLADDR 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=${old_LIBS}
+
 
 # do the package library checks now
 
@@ -19918,6 +20016,281 @@ echo "$as_me: *** Please correct the installation" >&6;}
 echo "$as_me: *** Either correct the installation, or run configure" >&6;}
          { echo "$as_me:$LINENO: *** without explicitly specifying --with-${ALSA_OPTION}" >&5
 echo "$as_me: *** without explicitly specifying --with-${ALSA_OPTION}" >&6;}
+      fi
+      exit 1
+   fi
+fi
+
+
+
+if test "${USE_BFD}" != "no"; then
+   pbxlibdir=""
+   if test "x${BFD_DIR}" != "x"; then
+      if test -d ${BFD_DIR}/lib; then
+      	 pbxlibdir="-L${BFD_DIR}/lib"
+      else
+      	 pbxlibdir="-L${BFD_DIR}"
+      fi
+   fi
+   { echo "$as_me:$LINENO: checking for bfd_openr in -lbfd" >&5
+echo $ECHO_N "checking for bfd_openr in -lbfd... $ECHO_C" >&6; }
+if test "${ac_cv_lib_bfd_bfd_openr+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lbfd ${pbxlibdir}  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char bfd_openr ();
+int
+main ()
+{
+return bfd_openr ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_bfd_bfd_openr=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_bfd_bfd_openr=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_bfd_bfd_openr" >&5
+echo "${ECHO_T}$ac_cv_lib_bfd_bfd_openr" >&6; }
+if test $ac_cv_lib_bfd_bfd_openr = yes; then
+  AST_BFD_FOUND=yes
+else
+  AST_BFD_FOUND=no
+fi
+
+
+   if test "${AST_BFD_FOUND}" = "yes"; then
+      BFD_LIB="-lbfd "
+      BFD_HEADER_FOUND="1"
+      if test "x${BFD_DIR}" != "x"; then
+         BFD_LIB="${pbxlibdir} ${BFD_LIB}"
+	 BFD_INCLUDE="-I${BFD_DIR}/include"
+      fi
+      BFD_INCLUDE="${BFD_INCLUDE} "
+      saved_cppflags="${CPPFLAGS}"
+      CPPFLAGS="${CPPFLAGS} ${BFD_INCLUDE}"
+      if test "xbfd.h" != "x" ; then
+         if test "${ac_cv_header_bfd_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for bfd.h" >&5
+echo $ECHO_N "checking for bfd.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_bfd_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_bfd_h" >&5
+echo "${ECHO_T}$ac_cv_header_bfd_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking bfd.h usability" >&5
+echo $ECHO_N "checking bfd.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <bfd.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking bfd.h presence" >&5
+echo $ECHO_N "checking bfd.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <bfd.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: bfd.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: bfd.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: bfd.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: bfd.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: bfd.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: bfd.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: bfd.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: bfd.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: bfd.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: bfd.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to https://issues.asterisk.org ##
+## ------------------------------------------ ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for bfd.h" >&5
+echo $ECHO_N "checking for bfd.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_bfd_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_bfd_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_bfd_h" >&5
+echo "${ECHO_T}$ac_cv_header_bfd_h" >&6; }
+
+fi
+if test $ac_cv_header_bfd_h = yes; then
+  BFD_HEADER_FOUND=1
+else
+  BFD_HEADER_FOUND=0
+fi
+
+
+      fi
+      CPPFLAGS="${saved_cppflags}"
+      if test "x${BFD_HEADER_FOUND}" = "x0" ; then
+         if test -n "${BFD_MANDATORY}" ;
+         then
+            { echo "$as_me:$LINENO: ***" >&5
+echo "$as_me: ***" >&6;}
+            { echo "$as_me:$LINENO: *** It appears that you do not have the bfd development package installed." >&5
+echo "$as_me: *** It appears that you do not have the bfd development package installed." >&6;}
+            if test "x${BFD_OPTION}" = "x" ; then
+               { echo "$as_me:$LINENO: *** Please install it to include ${BFD_DESCRIP} support" >&5
+echo "$as_me: *** Please install it to include ${BFD_DESCRIP} support" >&6;}
+            else
+               { echo "$as_me:$LINENO: *** Please install it to include ${BFD_DESCRIP} support, or re-run configure" >&5
+echo "$as_me: *** Please install it to include ${BFD_DESCRIP} support, or re-run configure" >&6;}
+               { echo "$as_me:$LINENO: *** without explicitly specifying --with-${BFD_OPTION}" >&5
+echo "$as_me: *** without explicitly specifying --with-${BFD_OPTION}" >&6;}
+            fi
+            exit 1
+         fi
+         BFD_LIB=""
+         BFD_INCLUDE=""
+         PBX_BFD=0
+      else
+         PBX_BFD=1
+         cat >>confdefs.h <<_ACEOF
+#define HAVE_BFD 1
+_ACEOF
+      fi
+   elif test -n "${BFD_MANDATORY}";
+   then
+      { echo "$as_me:$LINENO: ***" >&5
+echo "$as_me: ***" >&6;}
+      { echo "$as_me:$LINENO: *** The ${BFD_DESCRIP} installation on this system appears to be broken." >&5
+echo "$as_me: *** The ${BFD_DESCRIP} installation on this system appears to be broken." >&6;}
+      if test "x${BFD_OPTION}" = "x" ; then
+         { echo "$as_me:$LINENO: *** Please correct the installation" >&5
+echo "$as_me: *** Please correct the installation" >&6;}
+      else
+         { echo "$as_me:$LINENO: *** Either correct the installation, or run configure" >&5
+echo "$as_me: *** Either correct the installation, or run configure" >&6;}
+         { echo "$as_me:$LINENO: *** without explicitly specifying --with-${BFD_OPTION}" >&5
+echo "$as_me: *** without explicitly specifying --with-${BFD_OPTION}" >&6;}
       fi
       exit 1
    fi
@@ -35935,6 +36308,10 @@ ALSA_LIB!$ALSA_LIB$ac_delim
 ALSA_INCLUDE!$ALSA_INCLUDE$ac_delim
 ALSA_DIR!$ALSA_DIR$ac_delim
 PBX_ALSA!$PBX_ALSA$ac_delim
+BFD_LIB!$BFD_LIB$ac_delim
+BFD_INCLUDE!$BFD_INCLUDE$ac_delim
+BFD_DIR!$BFD_DIR$ac_delim
+PBX_BFD!$PBX_BFD$ac_delim
 CAP_LIB!$CAP_LIB$ac_delim
 CAP_INCLUDE!$CAP_INCLUDE$ac_delim
 CAP_DIR!$CAP_DIR$ac_delim
@@ -36017,10 +36394,6 @@ OGG_DIR!$OGG_DIR$ac_delim
 PBX_OGG!$PBX_OGG$ac_delim
 OPENAIS_LIB!$OPENAIS_LIB$ac_delim
 OPENAIS_INCLUDE!$OPENAIS_INCLUDE$ac_delim
-OPENAIS_DIR!$OPENAIS_DIR$ac_delim
-PBX_OPENAIS!$PBX_OPENAIS$ac_delim
-OPENR2_LIB!$OPENR2_LIB$ac_delim
-OPENR2_INCLUDE!$OPENR2_INCLUDE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -36062,6 +36435,10 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+OPENAIS_DIR!$OPENAIS_DIR$ac_delim
+PBX_OPENAIS!$PBX_OPENAIS$ac_delim
+OPENR2_LIB!$OPENR2_LIB$ac_delim
+OPENR2_INCLUDE!$OPENR2_INCLUDE$ac_delim
 OPENR2_DIR!$OPENR2_DIR$ac_delim
 PBX_OPENR2!$PBX_OPENR2$ac_delim
 OSPTK_LIB!$OSPTK_LIB$ac_delim
@@ -36155,10 +36532,6 @@ PBX_VPB!$PBX_VPB$ac_delim
 ZLIB_LIB!$ZLIB_LIB$ac_delim
 ZLIB_INCLUDE!$ZLIB_INCLUDE$ac_delim
 ZLIB_DIR!$ZLIB_DIR$ac_delim
-PBX_ZLIB!$PBX_ZLIB$ac_delim
-ZAPTEL_LIB!$ZAPTEL_LIB$ac_delim
-ZAPTEL_INCLUDE!$ZAPTEL_INCLUDE$ac_delim
-ZAPTEL_DIR!$ZAPTEL_DIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -36200,6 +36573,10 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PBX_ZLIB!$PBX_ZLIB$ac_delim
+ZAPTEL_LIB!$ZAPTEL_LIB$ac_delim
+ZAPTEL_INCLUDE!$ZAPTEL_INCLUDE$ac_delim
+ZAPTEL_DIR!$ZAPTEL_DIR$ac_delim
 PBX_ZAPTEL!$PBX_ZAPTEL$ac_delim
 ALLOCA!$ALLOCA$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
@@ -36210,6 +36587,7 @@ GC_LDFLAGS!$GC_LDFLAGS$ac_delim
 AST_DECLARATION_AFTER_STATEMENT!$AST_DECLARATION_AFTER_STATEMENT$ac_delim
 AST_FORTIFY_SOURCE!$AST_FORTIFY_SOURCE$ac_delim
 AST_NO_STRICT_OVERFLOW!$AST_NO_STRICT_OVERFLOW$ac_delim
+PBX_DLADDR!$PBX_DLADDR$ac_delim
 PBX_DAHDI_TRANSCODE!$PBX_DAHDI_TRANSCODE$ac_delim
 GSM_INTERNAL!$GSM_INTERNAL$ac_delim
 KDEINIT!$KDEINIT$ac_delim
@@ -36241,7 +36619,7 @@ GTK2_LIB!$GTK2_LIB$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 44; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
